import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/provider/Providers";
import SidebarContainer from "@/app/(main)/_components/SidebarContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex min-h-screen">
            <div className="w-64 h-screen bg-gray-800">
              <SidebarContainer />
            </div>
            <main className="flex-1 h-screen">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
